# Generated by Django 6.0.3 on 2026-04-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
                ('url', models.CharField(max_length=500)),
                ('data_collected', models.TextField()),
                ('third_party_sharing', models.TextField()),
                ('your_rights', models.TextField()),
                ('cancellation_refund_policy', models.TextField()),
                ('red_flags', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
